version: '3.8'

services:
  back:
    build:
      context: ./back
    container_name: back
    ports:
      - "3000:3000"
    networks:
      - app-network

  front:
    build:
      context: ./front
    container_name: front
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
